<a href="https://colab.research.google.com/github/DeepakDayanandan1/AI-ML-Intership/blob/main/AI_ML_Day1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Welcome to the session.")

Welcome to the session.


In [ ]:
"hello"

'hello'

In [ ]:
66

66

In [ ]:
print("Welcome","to","the","session",sep="-")

Welcome-to-the-session


In [ ]:
age="45"
type(age)

str

In [ ]:
tot_revenue = 3500
name = "Roses and Lillies"
print(name,tot_revenue,sep="-")

Roses and Lillies-3500


In [ ]:
print(f"my business name is {name} and my revenue is {tot_revenue}")

my business name is Roses and Lillies and my revenue is 3500


In [ ]:
print("my business {} has revenue of {} rupees".format(name,tot_revenue))

my business Roses and Lillies has revenue of 3500 rupees


In [ ]:
name2 = int(input("What is your age:"))
print(type(name2))

What is your age:45
<class 'int'>


In [ ]:
message = "Its good to see you all. Please come tomorrow. It will be good."
len(message)

63

In [ ]:
message[0:15]

'Its good to see'

In [ ]:
message[::-1]

'.doog eb lliw tI .worromot emoc esaelP .lla uoy ees ot doog stI'

In [ ]:
message.upper()

'ITS GOOD TO SEE YOU ALL. PLEASE COME TOMORROW. IT WILL BE GOOD.'

In [ ]:
message.lower()

'its good to see you all. please come tomorrow. it will be good.'

In [ ]:
message.title()

'Its Good To See You All. Please Come Tomorrow. It Will Be Good.'

In [ ]:
message.find("good")

4

In [ ]:
list = ["apple", "banana", "cherry"]
print(list)

['apple', 'banana', 'cherry']


In [ ]:
list = ["apple", "banana", "cherry"]
list.append("orange")
print(list)

['apple', 'banana', 'cherry', 'orange']


In [ ]:
list = ["apple", "banana", "cherry"]
list.remove("cherry")
print(list)

['apple', 'banana']


In [ ]:
list = ["apple", "cherry", "banana"]
list.sort
print(list)

['apple', 'cherry', 'banana']


In [ ]:
movies = [{"title":"Inception","year":2010,"ratings":[8,9,10,9]},
          {"title":"Titanic","year":1997,"ratings":[9,8,9,10]},
           {"title":"The Matrix","year":1999,"ratings":[10,9,10,10]},
            {"title":"Interstellar","year":2014,"ratings":[9,8,10,9]}]
print(movies)

[{'title': 'Inception', 'year': 2010, 'ratings': [8, 9, 10, 9]}, {'title': 'Titanic', 'year': 1997, 'ratings': [9, 8, 9, 10]}, {'title': 'The Matrix', 'year': 1999, 'ratings': [10, 9, 10, 10]}, {'title': 'Interstellar', 'year': 2014, 'ratings': [9, 8, 10, 9]}]


In [ ]:
movies.append({"title":"Deadpool","year":2024,"ratings":[9,10,10,9]})
print(movies)

[{'title': 'Inception', 'year': 2010, 'ratings': [8, 9, 10, 9]}, {'title': 'Titanic', 'year': 1997, 'ratings': [9, 8, 9, 10]}, {'title': 'The Matrix', 'year': 1999, 'ratings': [10, 9, 10, 10]}, {'title': 'Interstellar', 'year': 2014, 'ratings': [9, 8, 10, 9]}, {'title': 'Inception', 'year': 2010, 'ratings': [8, 9, 10, 9]}, {'title': 'Inception', 'year': 2010, 'ratings': [8, 9, 10, 9]}]


In [ ]:
for movie in movies:
    if movie["title"] == "Inception":
        movie["ratings"].extend([9, 10, 8])
print(movies[0])

{'title': 'Inception', 'year': 2010, 'ratings': [8, 9, 10, 9, 9, 10, 8]}


In [ ]:
for movie in movies:
  rating= sum(movie["ratings"])/len(movie["ratings"])
  print("Movie title:",movie["title"],"Average rating:",rating)

Movie title: Inception Average rating: 9.0
Movie title: Titanic Average rating: 9.0
Movie title: The Matrix Average rating: 9.75
Movie title: Interstellar Average rating: 9.0


In [ ]:
for movie in movies:
    if movie["title"] == "Inception":
        movie["title"] = "Cobra Kai"
print(movies)

[{'title': 'Cobra Kai', 'year': 2010, 'ratings': [8, 9, 10, 9, 9, 10, 8]}, {'title': 'Titanic', 'year': 1997, 'ratings': [9, 8, 9, 10]}, {'title': 'The Matrix', 'year': 1999, 'ratings': [10, 9, 10, 10]}, {'title': 'Interstellar', 'year': 2014, 'ratings': [9, 8, 10, 9]}]


In [ ]:
highest_rated = max(movies, key=lambda movie: movie["ratings"])
print("Highest rated movie:", highest_rated['title'], "with rating", highest_rated['ratings'])

Highest rated movie: The Matrix with rating [10, 9, 10, 10]


In [ ]:
movies.pop(1)
print(movies)

[{'title': 'Cobra Kai', 'year': 2010, 'ratings': [8, 9, 10, 9, 9, 10, 8]}, {'title': 'The Matrix', 'year': 1999, 'ratings': [10, 9, 10, 10]}, {'title': 'Interstellar', 'year': 2014, 'ratings': [9, 8, 10, 9]}]


In [ ]:
for movie in movies:
  rating= sum(movie["ratings"])/len(movie["ratings"])
  if rating >= 9:
    print("Movie:",movie["title"])

Movie: Cobra Kai
Movie: Titanic
Movie: The Matrix
Movie: Interstellar


In [ ]:
marks = [90, 40, 75, 52, 56]

#def calculate_average(marks_list):
 #   return sum(marks_list)/len(marks_list)

def assign_grade(mark):
    if mark >= 90:
        return 'A'
    elif mark >= 80:
        return 'B'
    elif mark >= 70:
        return 'C'
    elif mark >= 60:
        return 'D'
    else:
        return 'F'

#average = calculate_average(marks)

grades = [assign_grade(mark) for mark in marks]

print("Student's Marks:", marks)
print("Grades:", grades)
#print("Average Mark:", average)

Student's Marks: [90, 40, 75, 52, 56]
Grades: ['A', 'F', 'C', 'F', 'F']


In [ ]:
import numpy as np
my_list = [1,2,3,4]
type(my_list)

list

In [ ]:
my_array = np.array(my_list)
type(my_array)

numpy.ndarray

In [ ]:
my_arr = my_list

In [ ]:
my_array.shape

(4,)

In [ ]:
my_array.size

4

In [ ]:
my_array.ndim

1

In [ ]:
my_arr2 = np.array([[1,12,23,4],[5,26,17,8]])
my_arr2

array([[ 1, 12, 23,  4],
       [ 5, 26, 17,  8]])

In [ ]:
my_arr2.shape

(2, 4)

In [ ]:
my_arr2.size

8

In [ ]:
my_arr2 = np.array([[1,12,23,4],
                    [5,26,17,8],
                    [23,45,12,16]])
my_arr2

array([[ 1, 12, 23,  4],
       [ 5, 26, 17,  8],
       [23, 45, 12, 16]])

In [ ]:
my_arr2.shape

(3, 4)

In [ ]:
my_arr2.size

12

In [ ]:
np.sum(my_arr2)

np.int64(192)

In [ ]:
np.sort(my_arr2)

array([[  1,   4,  12,  23],
       [  5,   8,  17,  26],
       [183, 183, 183, 183]])

In [ ]:
my_arr2[1:,2:]

array([[ 17,   8],
       [183, 183]])

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
newarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
newarr = arr.reshape(2, 3, 2)
newarr

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [ ]:
a1 = np.array([[1,2],[3,1]])
a2 = np.array([[1,2],[3,1]])

a3 = a1 + a2
a3

array([[2, 4],
       [6, 2]])

In [ ]:
np.random.random((4,3))

array([[0.642347  , 0.87001814, 0.41094394],
       [0.77716112, 0.41662766, 0.66746041],
       [0.25876468, 0.1027247 , 0.44484792],
       [0.38862232, 0.56703538, 0.52173956]])

In [ ]:
np.random.randint(10,100,(2,6))

array([[15, 10, 19, 50, 76, 29],
       [84, 71, 38, 17, 38, 80]])